from typing import TypedDict,Annotated, List



class State(TypedDict):
    """
    Attributers:
    question: The question asked by the user
    generated_answer: The answer generated by the model
    we_searched: The websites searched by the model
    Document: Stored data from the websites searched by the model
    answer: The answer generated by the model

    """

    question: str
    generation: str
    web_search: bool
    documents: List[str]
    
